# Generated by Django 5.2.3 on 2026-02-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('free', 'Gratuito'), ('trial', 'Trial'), ('premium', 'Premium')], default='free', max_length=20, verbose_name='Tipo de Conta'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trial_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Trial Expira Em'),
        ),
    ]
