# Generated by Django 5.2.3 on 2025-07-14 23:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], max_length=1, verbose_name='Gênero')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, verbose_name='Telefone Secundário')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Rua')),
                ('number', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('current_position', models.CharField(blank=True, max_length=255, verbose_name='Cargo Atual')),
                ('current_company', models.CharField(blank=True, max_length=255, verbose_name='Empresa Atual')),
                ('education_level', models.CharField(blank=True, choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('tecnico', 'Técnico'), ('superior', 'Superior'), ('pos_graduacao', 'Pós-graduação'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado')], max_length=20, verbose_name='Nível de Escolaridade')),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Anos de Experiência')),
                ('desired_salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pretensão Salarial Mínima')),
                ('desired_salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pretensão Salarial Máxima')),
                ('professional_summary', models.TextField(blank=True, verbose_name='Resumo Profissional')),
                ('skills', models.TextField(blank=True, verbose_name='Habilidades e Competências')),
                ('certifications', models.TextField(blank=True, verbose_name='Certificações')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portfólio')),
                ('available_for_work', models.BooleanField(default=True, verbose_name='Disponível para Trabalho')),
                ('can_travel', models.BooleanField(default=False, verbose_name='Disponível para Viagens')),
                ('accepts_remote_work', models.BooleanField(default=True, verbose_name='Aceita Trabalho Remoto')),
                ('accepts_relocation', models.BooleanField(default=False, verbose_name='Aceita Mudança de Cidade')),
                ('preferred_work_shift', models.CharField(choices=[('morning', 'Manhã'), ('afternoon', 'Tarde'), ('night', 'Noite'), ('flexible', 'Flexível')], default='flexible', max_length=20, verbose_name='Turno Preferido')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil do Candidato',
                'verbose_name_plural': 'Perfis dos Candidatos',
            },
        ),
        migrations.CreateModel(
            name='CandidateExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('company', models.CharField(max_length=255, verbose_name='Empresa')),
                ('position', models.CharField(max_length=255, verbose_name='Cargo')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('is_current', models.BooleanField(default=False, verbose_name='Trabalho Atual')),
                ('description', models.TextField(verbose_name='Descrição das Atividades')),
                ('achievements', models.TextField(blank=True, verbose_name='Principais Conquistas')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='candidates.candidateprofile', verbose_name='Candidato')),
            ],
            options={
                'verbose_name': 'Experiência Profissional',
                'verbose_name_plural': 'Experiências Profissionais',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('institution', models.CharField(max_length=255, verbose_name='Instituição')),
                ('course', models.CharField(max_length=255, verbose_name='Curso')),
                ('degree', models.CharField(max_length=100, verbose_name='Grau')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('is_current', models.BooleanField(default=False, verbose_name='Está Cursando')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='candidates.candidateprofile', verbose_name='Candidato')),
            ],
            options={
                'verbose_name': 'Formação Acadêmica',
                'verbose_name_plural': 'Formações Acadêmicas',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CandidateLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('language', models.CharField(max_length=100, verbose_name='Idioma')),
                ('proficiency', models.CharField(choices=[('basic', 'Básico'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado'), ('fluent', 'Fluente'), ('native', 'Nativo')], max_length=20, verbose_name='Nível de Proficiência')),
                ('has_certificate', models.BooleanField(default=False, verbose_name='Possui Certificado')),
                ('certificate_name', models.CharField(blank=True, max_length=255, verbose_name='Nome do Certificado')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='candidates.candidateprofile', verbose_name='Candidato')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'unique_together': {('candidate', 'language')},
            },
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('skill_name', models.CharField(max_length=100, verbose_name='Nome da Habilidade')),
                ('level', models.CharField(choices=[('beginner', 'Iniciante'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado'), ('expert', 'Especialista')], max_length=20, verbose_name='Nível')),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Anos de Experiência')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_skills', to='candidates.candidateprofile', verbose_name='Candidato')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'unique_together': {('candidate', 'skill_name')},
            },
        ),
    ]
