# Generated by Django 5.2.3 on 2025-07-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='image_profile',
            field=models.ImageField(blank=True, upload_to='image_profile', verbose_name='Foto de Perfil'),
        ),
    ]
