# Generated by Django 5.2.3 on 2025-07-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidateprofile_image_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateeducation',
            name='file',
            field=models.FileField(blank=True, upload_to='file_education', verbose_name='Certiciado'),
        ),
    ]
