# Generated by Django 5.2.3 on 2025-09-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidateeducation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='city',
            field=models.CharField(default=1, max_length=500, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='state',
            field=models.CharField(default=1, max_length=2, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
