# Generated by Django 5.2.3 on 2025-09-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidateprofile_city_candidateprofile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateexperience',
            name='salary',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Salário'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='desired_salary_max',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Pretensão Salarial Máxima'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='desired_salary_min',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Pretensão Salarial Mínima'),
        ),
    ]
