# Generated by Django 5.2.3 on 2025-09-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_alter_candidateexperience_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateeducation',
            name='file',
            field=models.FileField(blank=True, upload_to='file_education', verbose_name='Certificado'),
        ),
    ]
