# Generated by Django 5.2.3 on 2025-11-17 15:14

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_alter_candidateeducation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateeducation',
            name='file',
            field=models.FileField(blank=True, upload_to=app.utils.UniqueFilePathGenerator('file_education'), verbose_name='Certificado'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='image_profile',
            field=models.ImageField(blank=True, upload_to=app.utils.UniqueFilePathGenerator('image_profile'), verbose_name='Foto de Perfil'),
        ),
    ]
