# Generated by Django 5.2.3 on 2026-02-01 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_alter_candidateeducation_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do Contato de Emergência'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone do Contato de Emergência'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='has_cnh',
            field=models.BooleanField(default=False, verbose_name='Possui CNH'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='has_vehicle',
            field=models.BooleanField(default=False, verbose_name='Possui Veículo'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_observations',
            field=models.TextField(blank=True, verbose_name='Observações do Recrutador'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Revisão'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_status',
            field=models.CharField(choices=[('pending', 'Em análise'), ('approved', 'Aprovado'), ('rejected', 'Reprovado'), ('changes_requested', 'Pendências')], default='pending', max_length=20, verbose_name='Status do Perfil'),
        ),
    ]
