# Generated by Django 5.2.3 on 2026-02-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_candidateprofile_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_status',
            field=models.CharField(choices=[('pending', 'Em análise'), ('awaiting_review', 'Aguardando Revisão'), ('approved', 'Aprovado'), ('rejected', 'Reprovado'), ('changes_requested', 'Aguardando Candidato')], default='pending', max_length=20, verbose_name='Status do Perfil'),
        ),
    ]
