# Generated by Django 5.2.3 on 2026-02-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_add_awaiting_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='accepts_whatsapp',
            field=models.BooleanField(default=True, verbose_name='Aceita mensagens via WhatsApp'),
        ),
    ]
