# Generated by Django 5.2.3 on 2026-02-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_candidateprofile_accepts_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
