# Generated by Django 5.2.3 on 2026-02-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_alter_candidateprofile_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='pending_observation_sections',
            field=models.JSONField(blank=True, default=list, verbose_name='Seções pendentes de edição'),
        ),
    ]
