# Generated by Django 5.2.3 on 2025-07-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Ocupação',
                'verbose_name_plural': 'Ocupações',
            },
        ),
        migrations.CreateModel(
            name='SpontaneousApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('resume', models.FileField(upload_to='resumes/', verbose_name='Currículo')),
                ('area_1', models.CharField(max_length=100, verbose_name='Área de Atuação 1 (Obrigatória)')),
                ('area_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área de Atuação 2')),
                ('area_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área de Atuação 3')),
            ],
            options={
                'verbose_name': 'Candidatura Espontânea',
                'verbose_name_plural': 'Candidaturas Espontâneas',
                'ordering': ['-created_at'],
            },
        ),
    ]
