# Generated by Django 5.2.3 on 2025-07-06 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spontaneous', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occupation',
            options={'ordering': ['code'], 'verbose_name': 'Ocupação', 'verbose_name_plural': 'Ocupações'},
        ),
    ]
