# Generated by Django 5.2.3 on 2025-07-06 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spontaneous', '0002_alter_occupation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spontaneousapplication',
            name='area_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupation_area1', to='spontaneous.occupation', verbose_name='Área de Atuação 1 (Obrigatória)'),
        ),
        migrations.AlterField(
            model_name='spontaneousapplication',
            name='area_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupation_area2', to='spontaneous.occupation', verbose_name='Área de Atuação 2'),
        ),
        migrations.AlterField(
            model_name='spontaneousapplication',
            name='area_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupation_area3', to='spontaneous.occupation', verbose_name='Área de Atuação 3'),
        ),
    ]
