# Generated by Django 5.2.3 on 2025-09-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spontaneous', '0004_spontaneousapplication_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spontaneousapplication',
            options={'ordering': ['-created_at'], 'permissions': [('view_all_spontaneousapplications', 'Pode visualizar todas as candidaturas espontâneas')], 'verbose_name': 'Candidatura Espontânea', 'verbose_name_plural': 'Candidaturas Espontâneas'},
        ),
        migrations.AddField(
            model_name='spontaneousapplication',
            name='cpf',
            field=models.CharField(default=1, max_length=14, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
