# Generated by Django 5.2.3 on 2025-09-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spontaneous', '0005_alter_spontaneousapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spontaneousapplication',
            name='street',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Rua'),
        ),
    ]
