# Generated by Django 5.2.3 on 2025-11-17 15:14

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spontaneous', '0006_spontaneousapplication_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spontaneousapplication',
            name='resume',
            field=models.FileField(upload_to=app.utils.UniqueFilePathGenerator('resumes'), verbose_name='Currículo'),
        ),
    ]
