# Generated by Django 5.2.3 on 2026-02-01 21:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0009_add_awaiting_review_status'),
        ('companies', '0004_alter_company_logo'),
        ('jobs', '0004_job_type_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('title', models.CharField(max_length=255, verbose_name='Título do Processo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('paused', 'Pausado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_processes', to='companies.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_selection_processes', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selection_processes', to='jobs.job', verbose_name='Vaga Vinculada')),
            ],
            options={
                'verbose_name': 'Processo Seletivo',
                'verbose_name_plural': 'Processos Seletivos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Etapa')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Ordem')),
                ('is_eliminatory', models.BooleanField(default=True, help_text='Se marcado, reprovação nesta etapa elimina o candidato do processo', verbose_name='Etapa Eliminatória')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='selection_process.selectionprocess', verbose_name='Processo Seletivo')),
            ],
            options={
                'verbose_name': 'Etapa do Processo',
                'verbose_name_plural': 'Etapas do Processo',
                'ordering': ['process', 'order'],
                'unique_together': {('process', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CandidateInProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('status', models.CharField(choices=[('pending', 'Aguardando Início'), ('in_progress', 'Em Andamento'), ('approved', 'Aprovado'), ('rejected', 'Reprovado'), ('withdrawn', 'Desistente')], default='pending', max_length=20, verbose_name='Status')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado Em')),
                ('recruiter_notes', models.TextField(blank=True, verbose_name='Observações do Recrutador')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_candidates_to_process', to=settings.AUTH_USER_MODEL, verbose_name='Adicionado Por')),
                ('candidate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_processes', to='candidates.candidateprofile', verbose_name='Perfil do Candidato')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_candidates', to='selection_process.processstage', verbose_name='Etapa Atual')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_in_process', to='selection_process.selectionprocess', verbose_name='Processo Seletivo')),
            ],
            options={
                'verbose_name': 'Candidato no Processo',
                'verbose_name_plural': 'Candidatos no Processo',
                'ordering': ['process', '-added_at'],
                'unique_together': {('process', 'candidate_profile')},
            },
        ),
        migrations.CreateModel(
            name='StageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('question_text', models.TextField(verbose_name='Texto da Pergunta')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Múltipla Escolha'), ('open_text', 'Texto Aberto')], max_length=20, verbose_name='Tipo de Pergunta')),
                ('options', models.JSONField(blank=True, help_text='Lista de opções em formato JSON: ["Opção 1", "Opção 2", ...]', null=True, verbose_name='Opções (para múltipla escolha)')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obrigatória')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='selection_process.processstage', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Pergunta da Etapa',
                'verbose_name_plural': 'Perguntas das Etapas',
                'ordering': ['stage', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CandidateStageResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('evaluation', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado na Etapa'), ('rejected', 'Reprovado na Etapa')], default='pending', max_length=20, verbose_name='Avaliação')),
                ('answers', models.JSONField(blank=True, help_text='JSON com question_id: answer', null=True, verbose_name='Respostas às Perguntas')),
                ('recruiter_feedback', models.TextField(blank=True, verbose_name='Feedback do Recrutador')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nota (1-10)')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='Avaliado Em')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Etapa Concluída')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluída Em')),
                ('candidate_in_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_responses', to='selection_process.candidateinprocess', verbose_name='Candidato no Processo')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Avaliado Por')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_responses', to='selection_process.processstage', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Resposta do Candidato na Etapa',
                'verbose_name_plural': 'Respostas dos Candidatos nas Etapas',
                'ordering': ['candidate_in_process', 'stage__order'],
                'unique_together': {('candidate_in_process', 'stage')},
            },
        ),
    ]
