# Generated by Django 5.2.3 on 2026-02-01 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_logo'),
        ('selection_process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectionprocess',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selection_processes', to='companies.company', verbose_name='Empresa'),
        ),
    ]
