# Generated by Django 5.2.3 on 2026-02-07 19:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_logo'),
        ('selection_process', '0002_alter_selectionprocess_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Modelo')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_templates', to='companies.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_process_templates', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
            ],
            options={
                'verbose_name': 'Modelo de Processo',
                'verbose_name_plural': 'Modelos de Processos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Etapa')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Ordem')),
                ('is_eliminatory', models.BooleanField(default=True, verbose_name='Etapa Eliminatória')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='selection_process.processtemplate', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Etapa do Modelo',
                'verbose_name_plural': 'Etapas do Modelo',
                'ordering': ['template', 'order'],
                'unique_together': {('template', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TemplateStageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('question_text', models.TextField(verbose_name='Texto da Pergunta')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Múltipla Escolha'), ('open_text', 'Texto Aberto')], max_length=20, verbose_name='Tipo de Pergunta')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='Opções (para múltipla escolha)')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obrigatória')),
                ('template_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='selection_process.templatestage', verbose_name='Etapa do Modelo')),
            ],
            options={
                'verbose_name': 'Pergunta do Modelo',
                'verbose_name_plural': 'Perguntas do Modelo',
                'ordering': ['template_stage', 'order'],
            },
        ),
    ]
