# Generated by Django 5.2.3 on 2026-02-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_seed_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='message_template',
            field=models.TextField(help_text='Variáveis disponíveis: {nome}, {observacoes}, {vaga}, {processo}, {documento}, {data_inicio}', verbose_name='Template da Mensagem'),
        ),
    ]
