# Generated by Django 5.2.3 on 2026-02-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_add_admission_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='status_event',
            field=models.CharField(choices=[('profile_approved', 'Perfil - Aprovado'), ('profile_rejected', 'Perfil - Reprovado'), ('profile_changes_requested', 'Perfil - Alterações Solicitadas'), ('process_added', 'Processo Seletivo - Candidato Adicionado'), ('process_approved', 'Processo Seletivo - Aprovado'), ('process_rejected', 'Processo Seletivo - Reprovado'), ('document_approved', 'Documento - Aprovado'), ('document_rejected', 'Documento - Rejeitado'), ('application_in_process', 'Candidatura - Em Processo'), ('application_interview', 'Candidatura - Entrevista Agendada'), ('application_approved', 'Candidatura - Aprovada'), ('application_rejected', 'Candidatura - Reprovada'), ('admission_started', 'Admissão - Iniciada'), ('admission_completed', 'Admissão - Dados Preenchidos'), ('admission_confirmed', 'Admissão - Confirmada')], max_length=40, unique=True, verbose_name='Evento de Status'),
        ),
    ]
