# Generated by Django 5.2.3 on 2025-07-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(default=1, max_length=500, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.CharField(max_length=2, verbose_name='Estado'),
        ),
    ]
