# Generated by Django 5.2.3 on 2025-07-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_name_alter_application_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Em análise'), ('in_process', 'Em processo seletivo'), ('approved', 'Aprovado'), ('rejected', 'Reprovado')], default='submitted', max_length=25, verbose_name='Status da Candidatura'),
        ),
    ]
