# Generated by Django 5.2.3 on 2025-11-17 15:14

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to=app.utils.UniqueFilePathGenerator('resumes'), verbose_name='Currículo'),
        ),
    ]
