# Generated by Django 5.2.3 on 2026-02-11 00:24

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, upload_to=app.utils.UniqueFilePathGenerator('resumes'), verbose_name='Currículo'),
        ),
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Estado'),
        ),
    ]
