# Generated by Django 5.2.3 on 2026-02-10 14:17

import app.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0012_add_pending_observation_sections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Documento')),
                ('description', models.TextField(blank=True, verbose_name='Descrição / Instruções')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('accepted_formats', models.CharField(default='pdf,jpg,png', help_text='Extensões separadas por vírgula, ex: pdf,jpg,png', max_length=100, verbose_name='Formatos Aceitos')),
                ('max_file_size_mb', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Tamanho Máximo (MB)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_types', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('file', models.FileField(upload_to=app.utils.UniqueFilePathGenerator('documents'), verbose_name='Arquivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome Original do Arquivo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=10, verbose_name='Status')),
                ('observations', models.TextField(blank=True, verbose_name='Observações do Recrutador')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da Revisão')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidates.candidateprofile', verbose_name='Candidato')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_documents', to='admission.documenttype', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Documento do Candidato',
                'verbose_name_plural': 'Documentos dos Candidatos',
                'ordering': ['document_type__order', 'document_type__name'],
                'unique_together': {('candidate', 'document_type')},
            },
        ),
    ]
