# Generated by Django 5.2.3 on 2025-07-03 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('title', models.CharField(max_length=255, verbose_name='Título da Vaga')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('location', models.CharField(max_length=255, verbose_name='Localização')),
                ('job_type', models.CharField(choices=[('full_time', 'Tempo Integral'), ('part_time', 'Meio Período'), ('internship', 'Estágio'), ('contract', 'Contrato Temporário')], max_length=20, verbose_name='Tipo de Contrato')),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='Faixa Salarial')),
                ('requirements', models.TextField(verbose_name='Requisitos')),
                ('responsibilities', models.TextField(verbose_name='Responsabilidades')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
            },
        ),
    ]
