# Generated by Django 5.2.3 on 2025-07-03 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='closure',
            field=models.DateField(default=datetime.datetime(2025, 7, 3, 18, 17, 10, 565824, tzinfo=datetime.timezone.utc), verbose_name='Encerramento da Vaga'),
            preserve_default=False,
        ),
    ]
