# Generated by Django 5.2.3 on 2025-07-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_closure'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default=1, max_length=500, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
