# Generated by Django 5.2.3 on 2025-07-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type_models',
            field=models.CharField(choices=[('in_person', 'Presencial'), ('home_office', 'Home Office'), ('hybrid', 'Hibrido')], default='in_person', max_length=20, verbose_name='Tipo de Modelo'),
            preserve_default=False,
        ),
    ]
