# Generated by Django 5.2.3 on 2025-07-03 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2025, 7, 3, 22, 58, 36, 775658, tzinfo=datetime.timezone.utc), max_length=500, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
