# Generated by Django 5.2.3 on 2025-11-17 15:14

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=app.utils.UniqueFilePathGenerator('logo'), verbose_name='Logo'),
        ),
    ]
